version: "3.7"

services:
  db:
    image: mysql:5.7.33
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  chrome:
    image: selenium/standalone-chrome:3.141.59
    volumes:
     - /dev/shm:/dev/shm

  base: &base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.ci
      cache_from:
        - base-development-cache
      args:
        ARG_RUBY_VERSION: ${ARG_RUBY_VERSION}
        ARG_BUNDLER_VERSION: ${ARG_BUNDLER_VERSION}
        ARG_APP_PATH: ${ARG_APP_PATH}
        ARG_RUBYGEMS_VERSION: ${ARG_RUBYGEMS_VERSION}
    image: base-development:${VERSION}
    tmpfs:
      - /tmp

  wait-middleware: &wait-middleware
    <<: *base
    environment:
      WAIT_HOSTS: db:3306,redis:6379,chrome:4444
      WAIT_TIMEOUT: 90
      WAIT_HOST_CONNECT_TIMEOUT: 10
      WAIT_BEFORE: 5
      WAIT_AFTER: 5
      WAIT_SLEEP_INTERVAL: 2
    depends_on:
      - db
      - redis
      - chrome
    command: /wait

  backend: &backend
    <<: *base
    stdin_open: true
    tty: true
    environment:
      HUB_URL: ${HUB_URL}
    depends_on:
      - db
      - redis

  console:
    <<: *backend
    command: /bin/bash

volumes:
  db-data:
  redis-data: