version: "3.7"

services:
  db:
    image: mysql:5.7.33
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  selenium:
    # Ubuntu 20.04.1 LTS
    image: selenium/standalone-chrome:3.141.59-20210422 # Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=

  web: &base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.ci
      cache_from:
        - base-development-cache
      args:
        ARG_RUBY_VERSION: ${ARG_RUBY_VERSION}
        ARG_BUNDLER_VERSION: ${ARG_BUNDLER_VERSION}
        ARG_APP_PATH: ${ARG_APP_PATH}
        ARG_RUBYGEMS_VERSION: ${ARG_RUBYGEMS_VERSION}
    environment:
      - SELENIUM_HOST=${SELENIUM_HOST}
      - SELENIUM_PORT=${SELENIUM_PORT}
      - TEST_APP_HOST=${TEST_APP_HOST}
      - TEST_APP_PORT=${TEST_APP_PORT}
    stdin_open: true
    tty: true
    image: base-development:${VERSION}
    tmpfs:
      - /tmp

  start-and-wait-for-services-to-be-up:
    build:
      context: .
      dockerfile: Dockerfile.wait
    environment:
      WAIT_HOSTS: web:3001,db:3306,redis:6379,selenium:4444
      WAIT_TIMEOUT: 90
      WAIT_HOST_CONNECT_TIMEOUT: 30
      WAIT_BEFORE: 2
      WAIT_AFTER: 0
      WAIT_SLEEP_INTERVAL: 1
    depends_on:
      - web
      - db
      - redis
      - selenium
    command: /wait

  backend: &backend
    <<: *base
    stdin_open: true
    tty: true

  console:
    <<: *backend
    command: /bin/bash

volumes:
  db-data:
  redis-data: